fix(FC2): change Category Type from String to Integer in Model
- Change the type of `Category` from `string` to `int` in `ChannelData` class.

System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.data.channel_data.category | LineNumber: 0 | BytePositionInLine: 2859.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.

Signed-off-by: CHEN, CHUN <jim60105@gmail.com>