fix: container name invalid
k8s.Autorest.HttpOperationException: Operation returned an invalid status code 'UnprocessableEntity', response body {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Job.batch \"ytdlpyvfcalhoalx0\" is invalid: spec.template.spec.containers[0].name: Invalid value: \"ytdlpyvfcalhoalx0_uploader\": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')","reason":"Invalid","details":{"name":"ytdlpyvfcalhoalx0","group":"batch","kind":"Job","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"ytdlpyvfcalhoalx0_uploader\": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')","field":"spec.template.spec.containers[0].name"}]},"code":422}

Signed-off-by: 陳鈞 <jim60105@gmail.com>