在啟動ytarchive ACI以前先檢查ACI是否存在
解決以下情形:
1. ACI啟動時間過長 (Youtube抽風時會發生)
2. 檢測到ACI不存在，把狀態調整回Scheduled
3. 五分鐘後啟動錄影，在這五分間ACI完成啟動
4. ACI已存在，409 Conflict

錯誤資訊:
Azure.RequestFailedException: Unable to edit or replace deployment 'ytarchivecdrautermhy': previous deployment from '3/1/2023 1:11:48 PM' is still active (expiration time is '3/8/2023 1:03:26 PM'). Please see https://aka.ms/arm-deploy-resources for usage details.
Status: 409 (Conflict)
ErrorCode: DeploymentActive

Content:
{"error":{"code":"DeploymentActive","message":"Unable to edit or replace deployment 'ytarchivecdrautermhy': previous deployment from '3/1/2023 1:11:48 PM' is still active (expiration time is '3/8/2023 1:03:26 PM'). Please see https://aka.ms/arm-deploy-resources for usage details."}}
   at Azure.ResourceManager.Resources.DeploymentsRestOperations.CreateOrUpdateAtScopeAsync(String scope, String deploymentName, ArmDeploymentContent content, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.ArmDeploymentCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String deploymentName, ArmDeploymentContent content, CancellationToken cancellationToken)
   at LivestreamRecorderService.SingletonServices.ACIService.CreateAzureContainerInstanceAsync(String template, Object parameters, String deploymentName, CancellationToken cancellation) in /src/SingletonServices/ACIService.cs:line 59
   at LivestreamRecorderService.Workers.RecordWorker.CreateACIStartRecordAsync(VideoService videoService, CancellationToken stoppingToken) in /src/Workers/RecordWorker.cs:line 189
   at LivestreamRecorderService.Workers.RecordWorker.ExecuteAsync(CancellationToken stoppingToken) in /src/Workers/RecordWorker.cs:line 103
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)